### PR TITLE
CB-13852: (iOS) Fix bug prevent error on getPosition

### PR DESCRIPTION
**Pull request by JuanSeBestia**
When I try to get the position of an audio that had an error while loading, the crash appose exponentially because it can not cast the time = none

### Platforms affected
iOS xx

### What does this PR do?

if the time is none, return the value of position at default = -1

### What testing has been done on this change?
It does not affect much, I tested it in my personal project

### Checklist
- [ x ] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [ x ] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change. (I don`t know)

### CODE REVIEW

**Comment by jcesarmobile** [comment]
Can you rebase the PR so it only shows your commit?

**Comment by jsdussanc** [comment]
ready, rebase to master

**Comment by jcesarmobile** [comment]
No, I can still see 11 commits, only yours should appear

**Comment by macdonst** [comment]
@jcesarmobile we can do a "squash and merge" for this PR then only one commit will show up.

**Comment by jcesarmobile** [comment]
@macdonst my problem is not with the number of commits, it's because it shows old commits that are already merged, so I think there is something wrong with the PR, but I'm not a git expert.
If you think an squash and merge will make it appear as only one commit from the PR author then I'm ok with it, but as there are multiple commit authors here not sure which one will show up as the author (maybe all?)

**Comment by macdonst** [comment]
@jcesarmobile yeah, squash and merge will make it one commit but if @jsdussanc wants to fix it they can:

```
git checkout master
git pull origin master
git checkout 5.0.x
git rebase master
git push --force jsdussanc 5.0.x
```

That should re-write the history so it appears clean.

**Comment by janpio** [comment]
Hey, I just fixed the problem that caused Android tests to fail in `master`. Could you rebase this PR please? This should get rid of the Android failures and possibly fix all test failures for this PR.

**Comment by janpio** [comment]
Closing and re-opening to trigger a new CI/test run with new PR merge.

**Review by erisu — APPROVED** [review]
LGTM, I cherry-picked the individual commit and placed it in a new PR #353

This PR will be resolved on merge or #353

**Pull request closed without merging**
