### PR TITLE
Fixing issues on Android 6.0

### PR DESCRIPTION
**Pull request by lucViana**

### CODE REVIEW

**Comment by drbeermann** [comment]
This fixes the callbacks for me, but I'm still having issues with playing multiple media files at the same time on Marshmallow. I'll have to spend some time digging into the guts of the plugin as it's causing issues for a few of our users right now. If anyone has any hints for where to look I'd greatly appreciate it.

**Comment by ghenry22** [comment]
Note that the first change in this PR is already included in master for v2.2.0, I have been testing with the second change also included and that combined with PR #72 has resolved my audio playback issues on Marshmallow where playback of local files was fine but playback of remote streaming files would fail 99% of the time silently.

Only catch with this is that you can't seek before the file is ready to play, but that was already the case for non-local files anyway and local files are ready to play pretty much instantly so no difference really.

Would recommend merging in the second change in this, it's only a single line commented out.

**Comment by ghenry22** [comment]
@purplecabbage there are 2 single line changes on this PR, one of which is already incorporated into master from another commit.  If the second one liner from here could be committed to trunk then this PR could be closed and media plugin would work normally on Marshmallow.

Seems like a very quick and easily resolution.  I have been using a fork of the plugin with change incorporated for around a month now (since I realised Marshmallow was broken!) with no issues.

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-media/pull/77/commits/b6da930531d556e5541dade40d9ba679694c951b)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/9/)

| Builder Name  | Console Output | Test Report | Device Logs  |
|     :---:     |     :---:      |   :---:     |     :---:    |
| [Windows 8.1 Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/9//label=windows-slave,platformName=windows-8.1-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/9//label=windows-slave,platformName=windows-8.1-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/9//label=windows-slave,platformName=windows-8.1-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/9//label=windows-slave,platformName=windows-8.1-store/artifact/) |
| [Windows 10  Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/9//label=windows-slave,platformName=windows-10-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/9//label=windows-slave,platformName=windows-10-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/9//label=windows-slave,platformName=windows-10-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/9//label=windows-slave,platformName=windows-10-store/artifact/) |
| [Windows 8.1 Phone]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/9//label=windows-slave,platformName=windows-8.1-phone/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/9//label=windows-slave,platformName=windows-8.1-phone/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/9//label=windows-slave,platformName=windows-8.1-phone/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/9//label=windows-slave,platformName=windows-8.1-phone/artifact/) |
| [iOS]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/9//label=mac-slave,platformName=ios/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/9//label=mac-slave,platformName=ios/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/9//label=mac-slave,platformName=ios/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/9//label=mac-slave,platformName=ios/artifact/) |
| [Android Mac]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/9//label=mac-slave,platformName=android/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/9//label=mac-slave,platformName=android/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/9//label=mac-slave,platformName=android/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/9//label=mac-slave,platformName=android/artifact/) |

**Comment by macdonst** [comment]
@lucViana thanks for the PR but we fixed it a different way.

**Pull request closed without merging**
