### PR TITLE
CB-14091: fix tests code for stream url and remove browser

### PR DESCRIPTION
**Pull request by knight9999**
### Platforms affected

Tests code only
Browser (test)
iOS (test)

### What does this PR do?

Removing Browser's play audio tests. (which fails)
Change test streaming mp3 file's url in iOS tests.

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [x] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by shazron** [comment]
One failure on android-4.4 on Travis. I'm not sure what our support matrix for Android is currently. @infil00p @macdonst ?

**Comment by knight9999** [comment]
@shazron  Strange error since I’ve only fixed the iOS portion. Maybe it’s an TravisCI error so could you re-run the test if that’s possible?

**Comment by shazron** [comment]
@knight9999 I'll close and re-open this PR to re-trigger Travis

**Comment by shazron** [comment]
Looks like `master` builds have been failing on Android for a while: https://github.com/apache/cordova-plugin-media/commits/master

**Comment by shazron** [comment]
Actually, looks like an `npm` issue `Callback called more than once`

**Comment by shazron** [comment]
See https://github.com/npm/npm/issues/9418#issuecomment-170244027

**Comment by knight9999** [comment]
It appears that the test version of node_js was still using 4.2 which have already been deprecated in other Cordova repos for example cordova-cli. I have upgraded the Travis CI yaml file to reflect this change and now use version 6.14.2. All tests except for the Android 4.4 are now passing.

**Comment by shazron** [comment]
Follow the discussion here: https://lists.apache.org/thread.html/3178fd3d36491e6e0777d8ee104de93e2aef09c7c3ec19dbbdbcbcc3@%3Cdev.cordova.apache.org%3E

**Comment by knight9999** [comment]
I have removed tests of streaming for Android 4.4.

Remark that I have used one test mp3 file `WEB_MP3_STREAM = 'https://cordova-develop.github.io/cordova-plugin-media/res/mozart_serenade4_01.mp3'`.  
This is because that the old mp3 file `WEB_MP3_STREAM = 'http://c22033-l.i.core.cdn.streamfarm.net/22033mdr/live/3087mdr_figaro/ch_classic_128.mp3'` is not available now.
If someone can copy the above mp3 file to the official site https://cordova.apache.org, please copy it.

**Comment by shazron** [comment]
I'm not sure we have the copyright, any files we put on Apache need to have the right license (Apache 2.0 or one of the approved licenses).

**Comment by knight9999** [comment]
I found the original testing mp3 file ch_classic_128.mp3 from web.archive.org. (https://web.archive.org/web/20170205201205if_/http://c22033-l.i.core.cdn.streamfarm.net/22033mdr/live/3087mdr_figaro/ch_classic_128.mp3)
I put this mp3 file on my repository and used it to test.
I removed previous streaming test mp3 file `https://cordova-develop.github.io/cordova-plugin-media/res/mozart_serenade4_01.mp3`.

If you can copy this file to the cordova official site (For example, https://cordova.apache.org/downloads/)

**Comment by shazron** [comment]
Sorry to be a stickler on this -- just because something is in the Wayback Machine, does not mean that it lacks copyright. Until we can assert what license the file is in (like any code contribution), we can't add it to Apache. For example, BlueZed.mp3 was an original creation by @purplecabbage, a Cordova Committer and PMC member and assigned to Apache. In any case, I'm sure we can find a public domain/Apache-2.0 licensed music sample somewhere.

For example, any of the clips here are public domain: https://musopen.org/

**Comment by purplecabbage** [comment]
Why you no like song? Is it rock too hard?

**Comment by knight9999** [comment]
Thanks shazron and purplecabbage,
I have updated the tests code to use BlueZedEx.mp3 file for each test.
Sorry, I can not make song.

**Comment by purplecabbage** [comment]
my song is really just 8 bars repeating for 60 seconds ... the word 'song' may be a bit of stretch ...

**Pull request merged**
