### PR TITLE
Add ability to play queue of songs in background mode

### PR DESCRIPTION
**Pull request by ttatarinov**

### CODE REVIEW

**Comment by d3orn** [comment]
any updates about this feature? Would be nice to have background playlists

**Comment by ghenry22** [comment]
Background playlists can already be achieved by handling you playlist in you code, but what is really interesting here is implementing avplayer instead of avaudioplayer for iOS which actually supports playing streaming media at last rather than downloading the whole thing to a temp file then playing.

With some clean up this could be a really big improvement for the media plugin on ios

**Comment by ghenry22** [comment]
This pull request could probably be closed.

I have added an updated pull request which implements avplayer for streaming audio which has no conflicts, the info in these PR's was very useful to get that moving.

There is already a seperate remote controls cordova plugin which allows you the handle setting metadata and receiving remote control events from the lock screen or control center.

I think it's better to leave that as a seperate plugin as it has a specific purpose which is not playing media and is also ios only.

**Comment by Alkashi** [comment]
Completely in phase with @ghenry22 
Using AVPlayer would be a great improvement.

**Pull request closed without merging**
