### PR TITLE
CB-10455 android: Adding permission helper to remove cordova-android 5.0.0 constraint

### PR DESCRIPTION
**Pull request by riknoll**
Left out of the first round by mistake

### CODE REVIEW

**Comment by riknoll** [comment]
@tony-- @infil00p @nikhilkh Please review

**Comment by riknoll** [comment]
Tested on Marshmallow device and KitKat emulator using mobilespec media auto tests. Did tests using cordova-android's master and cordova-android 4.0.0

**Comment by infil00p** [comment]
LGTM

**Comment by riknoll** [comment]
Thanks. Also FYI I did the tests including #78 which I plan to merge shortly. Tests fail without it.

**Pull request merged**
