### PR TITLE
CB-12157: (android): Fix java.lang.NullPointerException on resumeAllGainedFocus

### PR DESCRIPTION
**Pull request by frankkoenigstein**
### Platforms affected
- Android

### What does this PR do?
fix issue in AudioPlayer when file is null:

```java
if (this.audioFile.compareTo(file) == 0) {
```

```java
11-16 16:13:11.071 E/AndroidRuntime(30650): FATAL EXCEPTION: JavaBridge
11-16 16:13:11.071 E/AndroidRuntime(30650): java.lang.NullPointerException
11-16 16:13:11.071 E/AndroidRuntime(30650):     at org.apache.cordova.media.AudioPlayer.readyPlayer(AudioPlayer.java:583)
11-16 16:13:11.071 E/AndroidRuntime(30650):     at org.apache.cordova.media.AudioPlayer.startPlaying(AudioPlayer.java:299)
11-16 16:13:11.071 E/AndroidRuntime(30650):     at org.apache.cordova.media.AudioHandler.resumeAllGainedFocus(AudioHandler.java:414)
11-16 16:13:11.071 E/AndroidRuntime(30650):     at org.apache.cordova.media.AudioHandler$1.onAudioFocusChange(AudioHandler.java:431)
11-16 16:13:11.071 E/AndroidRuntime(30650):     at android.media.AudioManager$FocusEventHandlerDelegate$1.handleMessage(AudioManager.java:2044)
11-16 16:13:11.071 E/AndroidRuntime(30650):     at android.os.Handler.dispatchMessage(Handler.java:102)
11-16 16:13:11.071 E/AndroidRuntime(30650):     at android.os.Looper.loop(Looper.java:136)
11-16 16:13:11.071 E/AndroidRuntime(30650):     at android.os.HandlerThread.run(HandlerThread.java:61)
```
This happens in AudioHandler in resumeAllGainedFocus. startPlaying was called with null.

### What testing has been done on this change?
Caused resumeAllGainedFocus was called and resumePlaying is called.

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully.

**Commit**     - [Link](https://github.com/apache/cordova-plugin-media/pull/122/commits/dbb4847d706ba52f03d9ccb209ae60f8d5167921)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/85/)

| Builder Name  | Console Output | Test Report | Device Logs  |
|     :---:     |     :---:      |   :---:     |     :---:    |
| [Windows 8.1 Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/85//PLATFORM=windows-8.1-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/85//PLATFORM=windows-8.1-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/85//PLATFORM=windows-8.1-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/85//PLATFORM=windows-8.1-store/artifact/) |
| [Windows 10  Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/85//PLATFORM=windows-10-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/85//PLATFORM=windows-10-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/85//PLATFORM=windows-10-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/85//PLATFORM=windows-10-store/artifact/) |
| [Windows 8.1 Phone]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/85//PLATFORM=windows-8.1-phone/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/85//PLATFORM=windows-8.1-phone/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/85//PLATFORM=windows-8.1-phone/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/85//PLATFORM=windows-8.1-phone/artifact/) |
| [iOS]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/85//PLATFORM=ios/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/85//PLATFORM=ios/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/85//PLATFORM=ios/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/85//PLATFORM=ios/artifact/) |
| [Android]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/85//PLATFORM=android/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/85//PLATFORM=android/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/85//PLATFORM=android/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-media-pr/85//PLATFORM=android/artifact/) |

**Comment by youhammi** [comment]
Please I have this issue but with different error stack like below: 
`Exception java.lang.RuntimeException: Unable to destroy activity {com.sayoo.challenge/com.sayoo.challenge.MainActivity}: java.util.ConcurrentModificationException
android.app.ActivityThread.performDestroyActivity (ActivityThread.java:4199)
android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:4217)
android.app.ActivityThread.access$1500 (ActivityThread.java:177)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1502)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:145)
android.app.ActivityThread.main (ActivityThread.java:5942)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1400)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1195)
arrow_drop_down
Caused by java.util.ConcurrentModificationException:
java.util.HashMap$HashIterator.nextEntry (HashMap.java:787)
java.util.HashMap$ValueIterator.next (HashMap.java:819)
org.apache.cordova.media.AudioHandler.onDestroy (AudioHandler.java:198)
org.apache.cordova.PluginManager.onDestroy (PluginManager.java:298)
org.apache.cordova.CordovaWebViewImpl.handleDestroy (CordovaWebViewImpl.java:480)
org.apache.cordova.CordovaActivity.onDestroy (CordovaActivity.java:305)
android.app.Activity.performDestroy (Activity.java:6519)
android.app.Instrumentation.callActivityOnDestroy (Instrumentation.java:1154)
android.app.ActivityThread.performDestroyActivity (ActivityThread.java:4177)
android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:4217)
android.app.ActivityThread.access$1500 (ActivityThread.java:177)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1502)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:145)
android.app.ActivityThread.main (ActivityThread.java:5942)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1400)`

Please your help o figure out the problem, and also when the previous merge could be on official version

**Comment by Venkat-TTapp** [comment]
Hi,
Please let me know if this is not the right place to report this bug/issue.

My app crashed 6 times when user return to back to content from Admob video ads. This happens only with video ads.

Below is the code from firebase:
```
NullPointerException - AudioPlayer.readyPlayer

Exception java.lang.NullPointerException:
org.apache.cordova.media.AudioPlayer.readyPlayer (AudioPlayer.java:583)
org.apache.cordova.media.AudioPlayer.startPlaying (AudioPlayer.java:299)
org.apache.cordova.media.AudioHandler.resumeAllGainedFocus (AudioHandler.java:414)
org.apache.cordova.media.AudioHandler$1.onAudioFocusChange (AudioHandler.java:431)
android.media.AudioManager$FocusEventHandlerDelegate$1.handleMessage (AudioManager.java:1984)
android.os.Handler.dispatchMessage (Handler.java:110)
android.os.Looper.loop (Looper.java:193)
android.app.ActivityThread.main (ActivityThread.java:5333)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:824)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:640)
dalvik.system.NativeStart.main (NativeStart.java)
```

****************
Similar error:
```
NullPointerException - String.compareTo

Exception java.lang.NullPointerException: rhs == null

java.lang.String.compareTo (String.java)
org.apache.cordova.media.AudioPlayer.readyPlayer (AudioPlayer.java:583)
org.apache.cordova.media.AudioPlayer.startPlaying (AudioPlayer.java:299)
org.apache.cordova.media.AudioHandler.resumeAllGainedFocus (AudioHandler.java:414)
org.apache.cordova.media.AudioHandler$1.onAudioFocusChange (AudioHandler.java:431)
android.media.AudioManager$FocusEventHandlerDelegate$1.handleMessage (AudioManager.java:2228)
android.os.Handler.dispatchMessage (Handler.java:111)
android.os.Looper.loop (Looper.java:207)
android.app.ActivityThread.main (ActivityThread.java:5776)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:789)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:679)
```



If you need further information please let me know.

Regards,
Venkat

**Comment by frankkoenigstein** [comment]
Hi, that looks quite familiar.
I think this is the right place.

Regards,
Frank

-------------------------------------------------------
Frank K�nigstein
dff solutions GmbH
Berliner Stra�e 12
D - 37073 G�ttingen
Telefon + 49 (0) 551 900 37 98
Telefax + 49 (0) 551 900 37 99
www.dff-solutions.de
dff solutions GmbH
Firmensitz: Berliner Str. 12, 37073 G�ttingen
Registergericht: Amtsgericht G�ttingen, HRB 3109
Gesch�ftsf�hrer: Felix Dossmann, Dr. Ralf Itter

________________________________________

**Comment by ryanagler** [comment]
My app also crashes from this issue.  Applying the changes from frankkoenigstein fixes it.  Please merge to main!

**Comment by ghenry22** [comment]
So I have started to encounter the problem this fixes recently.  Using runkeeper along with my music app runkeeper will take the audio focus for it's announcements.  If it happens to do this just as your media is being released or created then when it hands the focus back the app will fail as it will call play on a media that wasn't successfully created.

Would be good to get this merged as it has resolved this issue for me on Android with no side effects that I have noticed.

**Comment by ghenry22** [comment]
@shazron - this would be a great one to get in, I am having this issue frequently now on android with more apps having audible announcements and prompts.  Nothing like having your music player crash mid run to annoy you!

**Comment by shazron** [comment]
@ghenry22 I'm the last one to comment on an Android patch. perhaps @infil00p can chime in on reviewing this? I can merge if its approved

**Comment by ghenry22** [comment]
@shazron thanks, sorry to bug you just figured you were kind of the gatekeeper here.

@infil00p I have been running with this PR (and the other null point PR that was recently added) for a few days in all my apps testing and all works well.  This has resolved the issue where another app taking audio focus just as a create/release of media was happening would cause the media plugin to throw a null pointer.  I have not seen any ill effects and I can no longer reproduce the issue.

Have tested on Android 5/6 on a 3 different devices and all good so far.

**Comment by shazron** [comment]
After conferring with @infil00p, I tested with `cordova-paramedic`, everything passes, so I'm pulling this in.

**Comment by gustavo-iniguez-goya** [comment]
Hi all,

This problem has appeared also on my app. I applied the fix and seems to be fixed. Thanks!

**Comment by Venkat-TTapp** [comment]
Hi,

I am having the issue in most of my apps, can anyone please let me know how to apply this fix?

Is this fix applied at plugin level

or 

should I do any code change to apply this fix?

Please let me know, I am not aware of this process.

Regards,
Venkat

**Pull request closed without merging**
