### PR TITLE
Streaming & Background threading on play

### PR DESCRIPTION
**Pull request by ghenry22**
This fixes 2 issues in the Cordova Jira, both with iOS.  It enables streaming support for media playback from URLs while retaining the existing playback for local media.

The second part is the simply background thread the play function so it doesn't block the ui or lock up the app on load.  Gets rid of some of those pesky warnings in xcode too.

Tested with simulator and on iphone 5 and iphone 6 and ipad 2, with iOS 8.1, 8.3 & 8.4

Please merge these and bump the version of the media plugin so I can stop installing them from my own fork :)

Fix for CB-57
Updated to use avplayer when url starts with http:// or https:// for
full streaming support.

All other urls will use the standard AVAudioplayer

Fix for CB-8222
Background thread on play to prevent locking during initial load of
media.

### CODE REVIEW

**Comment by johncblandii** [comment]
I tested this on my app and the playback starts and pauses as expected.

+1

**Comment by nbazzeghin** [comment]
Been testing this and the stop() method does not seem to work, I had to use pause() to get the audio to actually stop when streaming an mp3 file.

**Comment by ghenry22** [comment]
avplayer which is used for streaming does not have an equivalent stop method.  You can just pause() and then release() there is no need to stop().

**Comment by nbazzeghin** [comment]
Awesome thanks!

**Comment by purplecabbage** [comment]
The API includes stop, if pause+release is the same thing, then your code should do that!
Otherwise you are breaking an api and forcing developers to change their app code.

**Comment by ghenry22** [comment]
I'll look and putting something in that mimics the existing stop behavior applied to avaudioplayer.

Any chance of this actually getting merged once that is done?

**Comment by Alkashi** [comment]
Hi,
Is there any news about the merge ?

**Comment by leon** [comment]
+1
Please merge this :)

**Comment by ghenry22** [comment]
Alkashi - getDuration definitely works as expected on ios devices.  I use it every day in my app and have tested it extensively on multiple devices and on the simulator.

**Comment by Alkashi** [comment]
@ghenry22 OK Thanks for the feedback I'll try again asap.

**Comment by Alkashi** [comment]
@ghenry22 I just tested and the getDuration() method which is supposed to return the total length of the mp3 file return me always 0.
Tested on iPhone 6 - iOS9

**Comment by ghenry22** [comment]
This pull request doesn't make any changes to the behavior of get duration calls though, I see with my media some times 0 is returned for some files sometimes it's a full duration, seems to vary depending on what information is available in the file or stream.

**Comment by nbazzeghin** [comment]
@Alkashi Im using this same code on iOS 9 and its working properly. Here is a code snippet on what I am doing.

```javascript
function onPlayerStatus(status) {
    console.log("onPlayerStatus:" + status);
    if (status == 2) {
        $('#btnPlay').addClass("btn-play-active");
        currentDuration = player.getDuration();
        console.log("CURRENT DURATION: " + currentDuration);
        updateMetas(mediaButton.data('title'),section);
    } else if (status == 4) {
        clearInterval(mediaTimer);
        mediaTimer = null;
        $('#btnPlay').removeClass("btn-play-active");
        $('#circProgress').circleProgress('value', 0);
    }
};
```

**Comment by blakedietz** [comment]
+1 for @ghenry22 's fix all you have to do is run a `cordova plugin rm cordova-plugin-media` and then `cordova plugin add https://github.com/ghenry22/cordova-plugin-media.git#avplayer_streaming` and streaming from a remote source such as soundcloud works.

**Comment by dts** [comment]
Good stuff - only downside is it currently always reports '0' as the duration of the resource.

**Comment by ghenry22** [comment]
@dts - thanks for the suggestion, I have implemented this and hopefully also fixed for playback from local files as well.

@purplecabbage - updated with implementation for stop() for compliance as requested.

incremented the version number so that I can see which version is actually installed.  if you install from my branch it should show version 1.0.3-dev when you run cordova plugin list.

**Comment by Alkashi** [comment]
OK so I was not completely crazy. Many thanks to @ghenry22 and others.

**Comment by ghenry22** [comment]
Alkashi - nope you were quite right.  I realised I had a different branch of the plugin installed myself to test some things for Android and it was giving me correct durations,  Hence I bumped the version number so I could see what I have running!

**Comment by nbazzeghin** [comment]
@alkashi @ghenry22 I did the same thing, at some point I patched the version that I'm using in my project. Oops :)

**Comment by ghenry22** [comment]
PR #12 & PR #18 could also be closed out as duplicate once this one is merged which will help to clean up some older lingering PR's

**Comment by filfat** [comment]
@ghenry22 It appears that seekTo wont work (at least not on SoundCloud streams) while it works on all the other platforms except the browser.
Is this expected behavior?

Cheers.

**Comment by filfat** [comment]
@ghenry22 speaking of which I just had a few cases right now of the tracking restarting from the start by itself without resetting the current time.

Cheers.

**Comment by ghenry22** [comment]
Not sure about soundcloud as I haven't tried to stream from them before.  Whether you can seek in a stream or not would probably depend on the source and the meta data it provides and if that is enough for the avplayer underlying framework of Apples to be happy.

One case I have come across on Android with some streams is that if the length of the stream is unknown it assigns it a length of 0 and then any attempt to seek or a stall in streaming and then resume will reset back to start, I haven't hit the same with iOS yet on those same streams but there are probably other quirks / scenarios where the iOS framework would have a similar issue.

**Comment by ghenry22** [comment]
seekTo definitely works on streams from other sources, my primary test is the subsonic media server but I have tried other random sources like free sample streams from spotify which also worked for me.

**Comment by filfat** [comment]
@ghenry22 It appears to be when the server doesn't return the proper content-length header, that it works on Android and Windows though makes me wonder if it would be possible to work around this or if I will have to download the whole track first on iOS (which isn't the greatest user experience as it takes a bit of time compared to streaming).

I'll reply with an example link from our Playstr.link backend soon :)

**Comment by filfat** [comment]
@ghenry22

Here's en example of what I'm talking about: "https://api.playstr.link/v1/stream/soundcloud/227708949.mp3".

seekTo works on Android & Windows but not in iOS (and webkit) as said in the post above this might be because of content-length missing but currently adding that on the backend isn't really plausible.

Any fixes or/and work-arounds would be greatly appreciated :D

**Comment by dduwab** [comment]
I'm having trouble hearing sound from a local mp3 on iOS. I can play a sound from a http:// address  but not from the local file tree www/assets/titleMusic.mp3
Resetting plugins due to page load. Log:
Finished load of: file:///Users/.../Devices/.../data/Containers/Bundle/Application/.../ccgame.app/www/main.html
Found resource '/Users/.../Devices/.../data/Containers/Bundle/Application/.../ccgame.app/www/assets/titleMusic.mp3' in the web folder.
Playing audio sample 'assets/titleMusic.mp3'
Playing stream with AVPlayer

Yet I don't hear any sound in this case. I'm new to iOS development but I did my best to trace through the code and no errors appeared and everything looked like it should be playing.
Again, there were no problems playing/hearing a file off the web.
Thanks.

**Comment by ghenry22** [comment]
It's trying to play a local file as a stream due to the path being used by the look of it.  Please try using the cordova.file.* paths to get a cdvfile:// path to your audio file and play with that path, should resolve your issue and make sure that your app works properly across platforms and installs as the path is consistent.

Check the file plugin for details on the file paths.

Cheers
Gaven

**Comment by dduwab** [comment]
@ghenry22 - no success yet, but it may be my problem since I'm still new to it.
But I'm wondering, shouldn't your changes not require client changes to be compatible with the main branch? Thanks.

**Comment by ghenry22** [comment]
@dduwab - this PR does not require any changes to the client at all, it all works exactly the same with all the same functions implemented in the same way.  You can swap back and forth easily between this PR and the released plugin.

I would suggest checking your file paths as per the file plugin documentation (media plugin uses the file plugin to access local files).  You don't want to use a full path like you have defined, you really want to use one of the cordova.file.* aliases to get the correct path to the file consistently.  Either way though you want to have file:// or cdvfile:// at the start of your path to the file as the plugin uses the prefix to determine whether the file is local or remote (this is the same in the master code as in this PR).

**Comment by snstarosciak** [comment]
@ghenry22 @dduwab - Hey guys, I'm glad to see I'm not the only one running into this issue. I, too, have run into an issue where I can't seem to play an mp3 file from my local device after it's been downloaded using the ngCordova File Transfer plugin for ionic. I'm using xCode 7.1 and iOS 9 and this is happening on both the emulator and my iPhone 6s plus. 

One thing I should note is that it works flawlessly on an android device, but for some reason iOS 9 doesn't want to play the audio. I can play the audio from an http:// address or from a directory inside www, but when it has file:// in front of it, it doesn't play, it doesn't give me an error, in fact, I've made a stackoverflow and ionic forum for this issue. I'm all out of options on this and I don't know what to do :/

Here is the post: http://stackoverflow.com/questions/33837326/ios-9-can-t-play-audio-video-files-that-are-downloaded-to-device

I should also note that I can't seem to play mp4 files in a <video> tag, when the source of the file is from my local device. This is actually separate from the media-plugin, but maybe there's some insight to be had from this problem as well. File Plugin? File Transfer plugin? I'm not sure. 

Thanks in advance :D

**Comment by ghenry22** [comment]
Ok this discussion isn't really relevant to this PR at all but more related to quirks of the file plugin that is used by the media plugin but let me try and help you out a bit:

https://github.com/apache/cordova-plugin-file

Read the info about file paths here and how to access persistent storage, cache storage etc.

Importantly look at the file paths for android, windows and ios and which cordova.file.* value they map to.  If you use cordova.file.dataDirectory for example it will work to map to persistent storage across all 3 platforms in a consistent way.  If you use file://somedir/someotherdir/etc then it won't work.

If you use file:// you will find that it also doesn't work on windows platform as it's native paths us ms-appdata:// prefixes.  Android works because it uses file:// paths for local files natively (the path mappings in the file plugin readme even show this).

So here's an example that might help you out from my code:

//define a variable to store the resolved path where files will be stored
      var basePath = false;

//get the path to the file to be used for later playback from file system
        var musicDirectory = cordova.file.dataDirectory + 'musicCache/';

//resolve the path to a usable internalURL for the current platform
        $window.resolveLocalFileSystemURL(musicDirectory, function(dir){
        if (!basePath) {
             basePath = dir.toInternalURL();
};
        })

**Comment by snstarosciak** [comment]
@ghenry22 - If I could hug you...I would squeeze you until you popped, like a balloon. I tested a combination of that code out with mine AND IT WORKED. I never thought there was light at the end of the tunnel with this problem haha thankyou so much :) I will answer this question on stackoverflow and accept it so people can also have their problems solved :+1: 

One more thing, does this function:

`$window.resolveLocalFileSystemURL(src, function(dir){
          basePath = dir.toInternalURL();
        });`

Only work for mp3 files or something, because I'm utilizing this for a .mov file but that function doesn't seem to resolve the URL for that, but will with an mp3 file. Any idea?

**Comment by ghenry22** [comment]
That function just gets the directory that you would store your files in.  You can then append any file name you want to access.  For example you could use the same with say pic.jpg to get a path to an image file to display, it's just a path to a file, doesn't matter what type of file.

I imagine you could then just use html5 video tags to play the video file, as long as it is in a format that the built in webview on the device can play.  You'd have to do some research though, I don't play any video in my apps so I really don't know the best way to handle it or encoding requirements.

Cheers
Gaven

**Comment by snstarosciak** [comment]
@ghenry22 Ahhh thankyou so much man, you've been a huge help :) :+1: Though I can get audio to work, I may need to try testing it in an HTML 5 audio player to see if it runs into a similar issue as an HTML video player with video files, but either way, at least one major problem fixed :P

Thanks dude!

**Comment by dduwab** [comment]
@ghenry22 Thanks for the great example, I got it working. I was using toURL() but changed it to toInternalURL() like your example. Now it plays the sounds.

**Comment by ghenry22** [comment]
@purplecabbage - if I fix the conflicts with the latest updates in master can this finally get merged?  I can't see any reason for this to be held back?

**Comment by ghenry22** [comment]
@dduwab @snstarosciak - glad I was able to help you guys out a bit. Good luck with your projects!

**Comment by purplecabbage** [comment]
@ghenry22 Absolutely!

**Comment by ghenry22** [comment]
@purplecabbage conflicts resolved was just the version bump I put in plugin.xml conflicting with the new version 2.0.0 bump in master, so completely trivial.

Please merge me :)

**Comment by johncblandii** [comment]
For real. This is a long running PR and should go through sooner than later.

**Comment by johncblandii** [comment]
Setting a rate for a stream shouldn't be a requirement.

**Comment by purplecabbage** [comment]
It IS an existing api. Granted you may think that background playback is more important, but it should not come with a tradeoff.

**Comment by johncblandii** [comment]
I understand that so long as testing rate changes is not a requirement for a stream.

**Comment by purplecabbage** [comment]
Testing master, all tests pass.
Testing this pr, one failing test.

**Comment by ghenry22** [comment]
The problem is the rate feature was added as a PR after this was submitted.  I have kept this branch up to date and merged those changes in but obviously they will only work with local file playback as the original author of the rate control features was working on a version of the media plugin that only used AVAudioPlayer.

I will have a look at setting playback rate for AVPlayer streaming sources and see what I can do about adding it.

**Comment by snstarosciak** [comment]
@ghenry22 Hellooo sir. I know this isn't really the appropriate place to ask this question, but it was the only way I knew I could contact you and have the question still be relevant. The media plugin stuff works great with iOS 9 :) 

My problem that I can't seem to solve, no matter how hard I try is basically trying to play a mp4 file in an HTML 5 video player like so:

`<video controls="controls" preload="metadata" webkit-playsinline="webkit-playsinline" >
            <source ng-src="{{resourceURL | trustAsResourceUrl}}" type="video/mp4"/>
          </video>`

resourceURL looks like "cdvfile://localhost/library-nosync/resources/resource-0/resource-0.mp4"

when I try playing the same exact video that I'm hosting from an external server, the video plays no problem in iOS 9.

Is there some kind of weird file system filepath issue I'm not thinking of? Do HTML 5 audio/video tags not like "ng-src"? Even when I try to do a direct src to the file in my emulator, it doesn't play. Since the html 5 video player only seems to work at all when running ionic emulate ios, instead of ionic emulate ios -lcs, I can't see any logs if it's spitting out an error, because it definitely isn't when I run it with -lcs.

Here is the code for trying to src it directly to the file that exists on the emulator (or at least when I run the emulator in -lcs mode)

`<video controls="controls" preload="metadata" webkit-playsinline="webkit-playsinline" >
            <source src="cdvfile://localhost/library-nosync/resources/resource-0/resource-0.mp4" type="video/mp4"/>
          </video>`

Are there any alternatives or things I can try? I'd love to answer my question in both the ionic and stackoverflow forums for other people who may have the same issue

**Comment by ghenry22** [comment]
@snstarosciak I'm not going to be much help to you on this one unfortunately.  The media plugin is for audio and my app only plays audio not video so I haven't messed around with the video stuff so much.

You may need to find something like this:
https://github.com/moust/cordova-plugin-videoplayer

I am not sure how well HTML5 video plays with cordova apps as I haven't really used it.

You could try using safari debug tools while running on the emulator or on a device to get the JS Console and see if there are any errors being spit out, you may be hitting whitelisting errors or CORS or something as well.

**Comment by snstarosciak** [comment]
@ghenry22 Oh man, this is great! I'll try this all out and let you know how it goes. I appreciate you nudging me into the right direction for stuff to try out and test :)

**Comment by nuruddinbadawi** [comment]
How Allow IOS Support Streaming?

**Comment by ghenry22** [comment]
@nuruddinbadawi install my branch of the media plugin with this command:

cordova plugin add https://github.com/ghenry22/cordova-plugin-media.git#avplayer_streaming

That will get you the version with streaming support

**Comment by nuruddinbadawi** [comment]
Skipping 'cordova-plugin-media' for android
"Plugin doesn't support this project's cordova-android version.
cordova-android: 4.1.1, failed version requirement: >=5.0.0-dev "

**Comment by ghenry22** [comment]
update your android platform and try again

**Comment by nuruddinbadawi** [comment]
in ios work fine but in android no

can install this brush just in ios and let android use default Media Plugin
because I don't have any problem with streaming in android

and thanks

**Comment by ghenry22** [comment]
@purplecabbage I have added rate control when streaming from a URL using avplayer and tested that it works.  However test case 19 still fails in the automated suite but I believe that is due to the way media is loaded and the success evaluator on the test.

To explain:
When setting rate to 0.5 and listening to a file it is audibly slower than normal playback rate.
When setting rate to 2.0 and listening to a file it is audibly faster than normal playback rate.
So rate can be set and adjusted and does change playback rate.

The problem with the test is it plays for 4 seconds and expects the playback position to be >7 when playing at rate 2.  This is fine when using the old avaudioplayer implementation as it will first download the entire file locally and then start paying immediately at rate 2, resulting in a final position generally around 8.

When using avplayer though to stream properly we don't download the entire file in advance, we only start streaming when play is pushed so we now have a variance that throws the test out.  If the file is slow to load from the source server for some reason we have a larger variance.  GIven only 4 seconds play time there is not enough time for the stream to start buffering and play at 2x rate in order to reach the magic test passing number.  This is completely normal and expected.

If the length of the test run was extended to say 10 seconds you would find a lot less variance as it allows some time to buffer.

If the mp3 source file is hosted on a local http server on the same machine running the emulator and tests it will also download almost instantly and pass the test. (I have tested this scenario).

To test rate you could potentially play for 4 seconds at rate 1 and then play for 4 seconds at rate 2 and if the output of the second play is close to 2x the first play then you have success.  Given that the tests are run one after the other they are likely to both have the same buffering time which mostly rules that out as a variable.

I am not sure how to rewrite the test to do this though.  If someone could help to rewrite the test then all tests will pass and this PR can finally get merged which would be fantastic!

**Comment by imsingh** [comment]
@ghenry22 Hey, I am not able to use the .m3u stream on iOS. I am getting following error.

2016-01-28 23:44:41.939 MPESG Radio[3073:44952] Failed to initialize AVAudioPlayer: The operation couldn’t be completed. (OSStatus error 1954115647.)
2016-01-28 23:44:41.940 MPESG Radio[3073:44952] THREAD WARNING: ['Media'] took '3625.225098' ms. Plugin should use a background thread.

**Comment by ghenry22** [comment]
@imsingh That doesn't really have anything to do with this pull request.  I'm not sure what "MPESG Radio" is that is generating the error messages, never seen that one before.  From my experience with the media plugin you need to give it a single file or single source URL to play, I don't think it will handle an m3u file with multiple items.  No idea what it would do with an m3u with multiple entries.

You could always grab the m3u file, strip out the list of items and then manage them as a playlist in your app code feeding them to the media plugin as sources appropriately.

**Comment by imsingh** [comment]
@ghenry22 MPESG Radio is just name of Cordova App and m3u file has a single URL entry. I Tried using the URL Directly again it is not working. However the plugin at https://github.com/keosuofficial/cordova-audio-stream-plugin works fine, but it has not implemented callbacks so I can't use it either.

**Comment by ghenry22** [comment]
@imsingh where are you loading the m3u file from?  If you are opening the m3u file from the local file system it will try to play it like a local file.  If you open it from a http url then it will try to stream it.  This is just the logic in the media plugin, it looks at the source prefix to determine if it should stream or play locally.

If you haven't already done so I have a fork of the plugin here that you can install using the command below, this fork has the updated ios streaming code from this pull request build in.  If you install from here and you're m3u file is being loaded from a url that starts with http or https you should see a message in the native console saying "playing stream with avplayer" instead of the normal message you see which is tied to "avaudioplayer".  avaudioplayer is the original implementation that does not support streaming, avplayer is the framework implemented in this PR to add proper streaming support.

cordova plugin add https://github.com/ghenry22/cordova-plugin-media.git#integrated_fixes

that's the best that I can think to recommend, hope it helps a bit!

**Comment by ghenry22** [comment]
@purplecabbage sorry to bug you but if you could have a look at my previous comment that would be great, I really want to get this merged as it has been hanging for a long time and is starting to be difficult to maintain my fork and keep everything up to date.

**Comment by purplecabbage** [comment]
Good to go. Thanks for sharing your work @ghenry22 !

**Comment by johncblandii** [comment]
Sweet!!

**Comment by ghenry22** [comment]
Awesome!  Glad I could contribute something back to the project!

**Comment by Taewa** [comment]
My streaming player got much faster. Thank you.
But I had to install this version through 
`sudo cordova plugin add cordova-plugin-media@2.2`

I originally tried with
`sudo cordova plugin add cordova-plugin-media`

But didn't work.

**Comment by purplecabbage** [comment]
We are further and further off topic, but 
Why are you using `sudo` to install plugins @Taewa ?

**Comment by ghenry22** [comment]
@purplecabbage comments on this PR could not possibly go further off topic :)  Seems to have become defacto media plugin support for a while there.

I had some odd permission issue on my mac initially and used sudo to install as well.  No matter what I did always had that problem, probably because I installed something early on with Sudo and then all the permissions became a mess.

Was resolved when I did a refresh of the OS on my mac and a clean install of all the tools without using sudo for anything.

Doesn't seem to hurt anything either way though and all build tools etc work.

**Comment by Taewa** [comment]
Hello @purplecabbage 
I actually didn't know why I had to use sudo. 
As @ghenry22 explained, I had odd permission problem. Some project had to use `sudo`, some are not.
I tried `chmod` but, couldn't resolve this issue

**Comment by purplecabbage** [comment]
Thanks @Taewa ! I was just curious.  I wonder how often this happens?! Never on windows ... ;)

**Comment by AshishMehra** [comment]
hi @ghenry22, must say your work here is stellar!

I have 2 issues with this plugin so far (i am using the latest pull from the main repo as your work is now merged there)

1) on iOS a streamling mp3 (30min long podcast) it can take upto 10secs for the track to start playing. On android it's no more than 2 seconds.. if i put the same link on a browser it will start playing in less than a second

2) if i only play local files or only streaming urls then its fine. if i stream something and then play a local file it will start playing the stream again - again only on ios. Android works fine so i know it's a plugin thing and not something in the code as it's the same code for both ( i do remove the "file://" for ios local tracks) 

Any help here would be immensely appreciated @ghenry22 . Many many thanks!

**Comment by nudou350** [comment]
Hey! I can't use the "cordova plugin add https://github.com/ghenry22/cordova-plugin-media.git#avplayer_streaming" command, it says:
npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE checkout avplayer_streaming
npm ERR! error: pathspec 'avplayer_streaming' did not match any file(s) known to git.

Am I missing something?

**Comment by purplecabbage** [comment]
That branch ( and this pr ) has been merged. @ghenry22 's branch no longer exists.
Just install via `cordova plugin add cordova-plugin-media`
https://github.com/ghenry22/cordova-plugin-media/branches

**Comment by nudou350** [comment]
Thanks for the info! But adding that works in browser and emulated android device. But when i try on a real device, it takes around 20s to start playing the stream! Any tips?

**Comment by onneti2013** [comment]
Hi use cordova plugin add cordova-plugin-media@2.2 solved slow start

**Pull request merged**
